In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import rand

df  = pd.DataFrame(rand( 50 , 3)*10, columns = 'Hours_Studied Hours_Slept IQ '.split())
df.head(2)

Hours_Studied  Hours_Slept        IQ
0       8.683276     2.548212  0.654974
1       4.301765     1.389066  2.704252

In [3]:
from random import choice

location = []
for i in range(50):
    
    location.append(choice(["New Delhi" , "Pune" , "Bangalore"]))
 
df['Location'] = location
df.head()

Hours_Studied  Hours_Slept        IQ   Location
0       8.683276     2.548212  0.654974  Bangalore
1       4.301765     1.389066  2.704252  New Delhi
2       9.511468     6.583568  3.100866       Pune
3       5.425553     1.577381  1.878998  Bangalore
4       1.548053     8.749571  7.148128  Bangalore

In [4]:
df['Marks'] = (1.73 + (3.34*df['Hours_Studied'])
                    + (2.45*df['Hours_Slept'])
                    + (1.83*df['IQ']  ))
df['Marks'] =  df['Marks'] +np.random.rand(50)*20
               
df.to_csv('Students.csv',index=False)
df.head()

Hours_Studied  Hours_Slept        IQ   Location      Marks
0       8.683276     2.548212  0.654974  Bangalore  48.409954
1       4.301765     1.389066  2.704252  New Delhi  39.193870
2       9.511468     6.583568  3.100866       Pune  73.962942
3       5.425553     1.577381  1.878998  Bangalore  27.704594
4       1.548053     8.749571  7.148128  Bangalore  52.505195

In [5]:
dataset = pd.read_csv('Students.csv')

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

[[8.68327629774228 2.548212385679609 0.6549738262807347 'Bangalore']
 [4.301765438504679 1.3890659073446388 2.704251592939948 'New Delhi']
 [9.511467673285182 6.583567853653554 3.100865584223096 'Pune']
 [5.425552500721487 1.577380724250992 1.8789982777196776 'Bangalore']
 [1.548052664325822 8.749570780370078 7.14812791614278 'Bangalore']
 [8.619668187030824 1.2913587546305183 4.358049832201491 'Pune']
 [6.81136614239095 8.908220018019918 0.9472245916068034 'Pune']
 [5.153279398945352 2.7978461891870454 5.727308730455571 'Pune']
 [1.705014968175651 7.435400621205002 9.35585594268465 'New Delhi']
 [4.437575677541801 5.391918863963172 3.724315294925878 'Bangalore']
 [1.7568783579420333 4.175094575543017 7.717454561829527 'New Delhi']
 [1.7133958151005702 0.7408955147465479 0.3186835455920778 'Pune']
 [2.705314817865111 1.5184355812507244 7.441538607168267 'New Delhi']
 [9.209286820689371 1.6717505921674023 2.381025073674534 'Bangalore']
 [1.227544011044995 2.5368213411116605 6.5260064253

In [6]:
print(y)

[48.40995393 39.19386954 73.96294188 27.70459428 52.50519525 52.20823609
 50.10291789 41.0477517  60.43548453 37.84186429 49.16933721 27.15086285
 39.59975864 55.1576668  25.84822856 80.59687856 26.69507101 47.76994084
 70.60017028 42.01120319 73.72941306 67.72783383 68.08929624 64.079973
 31.46920078 65.95340653 21.0956134  33.77986648 73.98676648 44.89621581
 38.587158   28.78835655 24.80693104 38.58834299 38.81958352 52.84892373
 45.68864122 54.04242956 65.02517398 23.27531438 47.68125343 26.09053855
 65.99137261 29.42122292 47.80690244 71.66422334 33.15522268 62.59748676
 58.89083816 77.40285065]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],  remainder='passthrough')
print(ct)

X = np.array(ct.fit_transform(X))

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [3])])


In [8]:
print(X)

[[1.0 0.0 0.0 8.68327629774228 2.548212385679609 0.6549738262807347]
 [0.0 1.0 0.0 4.301765438504679 1.3890659073446388 2.704251592939948]
 [0.0 0.0 1.0 9.511467673285182 6.583567853653554 3.100865584223096]
 [1.0 0.0 0.0 5.425552500721487 1.577380724250992 1.8789982777196776]
 [1.0 0.0 0.0 1.548052664325822 8.749570780370078 7.14812791614278]
 [0.0 0.0 1.0 8.619668187030824 1.2913587546305183 4.358049832201491]
 [0.0 0.0 1.0 6.81136614239095 8.908220018019918 0.9472245916068034]
 [0.0 0.0 1.0 5.153279398945352 2.7978461891870454 5.727308730455571]
 [0.0 1.0 0.0 1.705014968175651 7.435400621205002 9.35585594268465]
 [1.0 0.0 0.0 4.437575677541801 5.391918863963172 3.724315294925878]
 [0.0 1.0 0.0 1.7568783579420333 4.175094575543017 7.717454561829527]
 [0.0 0.0 1.0 1.7133958151005702 0.7408955147465479 0.3186835455920778]
 [0.0 1.0 0.0 2.705314817865111 1.5184355812507244 7.441538607168267]
 [1.0 0.0 0.0 9.209286820689371 1.6717505921674023 2.381025073674534]
 [1.0 0.0 0.0 1.2275440110

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
y_test

array([73.98676648, 27.15086285, 49.16933721, 26.09053855, 73.96294188,
       33.77986648, 65.02517398, 28.78835655, 68.08929624, 52.50519525])

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = regressor.predict(X_test)

np.set_printoptions(precision=2)
print("\n\n\nPredicted  Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))




Predicted  Actual
[[83.   73.99]
 [16.18 27.15]
 [42.75 49.17]
 [27.33 26.09]
 [63.04 73.96]
 [33.11 33.78]
 [58.33 65.03]
 [34.79 28.79]
 [62.42 68.09]
 [52.72 52.51]]


In [12]:
np.set_printoptions(precision=2)
print(np.concatenate((X_test ,y_pred.reshape(len(y_pred),1) ,y_test.reshape(len(y_test),1)) ,1))

[[0.0 0.0 1.0 9.0382710677679 9.34720610293322 9.678117325794434
  82.99508437006062 73.98676647944065]
 [0.0 0.0 1.0 1.7133958151005702 0.7408955147465479 0.3186835455920778
  16.183960081999157 27.150862847019727]
 [0.0 1.0 0.0 1.7568783579420333 4.175094575543017 7.717454561829527
  42.75266236719255 49.169337213536735]
 [0.0 0.0 1.0 3.231990494475255 0.458584170052444 3.4772150270549504
  27.33489519755266 26.090538553682197]
 [0.0 0.0 1.0 9.511467673285182 6.583567853653554 3.100865584223096
  63.041522567262774 73.9629418784159]
 [0.0 0.0 1.0 1.293417701451065 4.847887515335456 3.830448639463916
  33.108872801330136 33.779866478151256]
 [0.0 0.0 1.0 6.173247516788186 4.69596877712026 8.218349540889928
  58.33236161710652 65.02517398404561]
 [0.0 0.0 1.0 3.491783102617727 3.4031016569343 3.0041081062807526
  34.79041713522486 28.78835655106453]
 [0.0 0.0 1.0 7.531574074996766 4.33250111003953 8.475682905392434
  62.41816990383179 68.08929623990878]
 [1.0 0.0 0.0 1.548052664325822 

In [13]:
len(y_pred)

10

In [14]:
y_test

array([73.99, 27.15, 49.17, 26.09, 73.96, 33.78, 65.03, 28.79, 68.09,
       52.51])

In [15]:
y_pred

array([83.  , 16.18, 42.75, 27.33, 63.04, 33.11, 58.33, 34.79, 62.42,
       52.72])

In [16]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred) 

5.780523090003266